{
 "title": "servidores",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura Datacenter",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "keepAlive",
     "rawSql": "SELECT temperatura FROM keepAlive.Temperatura"
    }
   ]
  },
  {
   "title": "Temperatura esperada",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "keepAlive",
     "rawSql": "SELECT temp FROM keepAlive.broadlink"
    }
   ]
  },
  {
   "title": "Servidores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "keepAlive",
     "rawSql": "SELECT servidor_1, servidor_2, servidor_3, servidor_4, servidor_5, servidor_6, servidor_7, servidor_8 FROM keepAlive.pruebaestado"
    }
   ]
  },
  {
   "title": "Fecha ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "keepAlive",
     "rawSql": "SELECT fecha FROM keepAlive.broadlink"
    }
   ]
  }
 ]
}